<a href="https://colab.research.google.com/github/nhutHao02/ML_Lab/blob/main/Lab_3_20130252_TranNhutHao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Deadline: 23:59, 04/03/2023**

# Task 1. 
The main aim of this task is to get familiar with the tasks of preprocessing data using Scikit-learn â€“ a Python-based Machine Learning framework and Linear Regression.

For given 2 datasets (preprocessing_weather.csv, preprocessing_salary_dummy.csv), 
*   Identify issues with these datasets
*   Then, apply preprocessing techniques to the datasets

#Task 1.1. Dataset preprocessing_weather.csv

**Issues**:


1.   List item
2.   List item
3.   List item
4.   List item
....

**Preprocessing dataset**:

In [1]:

#code
from google.colab import drive
drive.mount('/content/gdrive')
%cd '/content/gdrive/MyDrive/ML_Lab'

Mounted at /content/gdrive
/content/gdrive/MyDrive/ML_Lab

In [2]:
#code
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.model_selection import train_test_split

In [3]:

dataset = pd.read_csv("preprocessing_weather.csv")
dataset.head(14)
impute = SimpleImputer(missing_values=np.nan, strategy='mean')
dataset[['temperature','humidity']] = impute.fit_transform(dataset[['temperature','humidity']])
dataset

    id   outlook  temperature   humidity  windy play
0    1     sunny    85.000000  85.000000  False   no
1    2     sunny    80.000000  90.000000   True   no
2    3  overcast    83.000000  86.000000  False  yes
3    4     rainy    73.846154  96.000000  False  yes
4    5     rainy    68.000000  80.000000  False  yes
5    6     rainy    65.000000  70.000000   True   no
6    7  overcast    64.000000  65.000000   True  yes
7    8     sunny    72.000000  95.000000  False   no
8    9     sunny    69.000000  82.538462  False  yes
9   10     rainy    75.000000  80.000000  False  yes
10  11     sunny    75.000000  70.000000   True  yes
11  12  overcast    72.000000  90.000000   True  yes
12  13  overcast    81.000000  75.000000  False  yes
13  14     rainy    71.000000  91.000000   True   no

#Task 1.2. Dataset preprocessing_salary_dummy.csv

**Issues**:


1.   List item
2.   List item
3.   List item
4.   List item
....

**Preprocessing dataset**:

In [4]:
#code
dataset = pd.read_csv("preprocessing_salary_dummy.csv")
dataset.head(10)
dataset.columns
impute = SimpleImputer(missing_values=np.nan, strategy='median')
dataset[[' Age', '   Salary ']] = impute.fit_transform(dataset[[' Age', '   Salary ']])
dataset

   No    Country   Age     Salary  Purchased
0   1     France  44.0     72000.0        No
1   2      Spain  27.0     48000.0       Yes
2   3    Germany  30.0     54000.0        No
3   4      Spain  38.0     61000.0        No
4   5    Germany  40.0     61000.0       Yes
5   6     France  35.0     58000.0       Yes
6   7      Spain  38.0     52000.0        No
7   8     France  48.0     79000.0       Yes
8   9    Germany  50.0     83000.0        No
9  10     France  37.0     67000.0       Yes

# **Task 2**. Simple Linear Regression in Scikit-Learn
---
# **Usage:**
> **Step 1**: build a model
![image.png]()

> **Step 2**: test the model

*   With test set:
`y_pred = regressor.predict(X_test)`

*   With a single value ("predict" method always expects a 2D array as the format of its inputs)
`regressor.predict([[12]])`

> **Step 3**: 
*   get w0, w1 , w2, â€¦,
-- W0: `regressor.intercept_`
-- w1, w2, â€¦: `regressor.coef_`
*   R^2 score: sum of squared r(i)
`r(i) = y(i) - f(x(i))`: residual of ith instance


> **Metrics**:
*   metrics.explained_variance_score(y_test, y_pred)
*   metrics.mean_absolute_error(y_ test, y_pred) 
*   metrics.mean_squared_error(y_ test, y_pred[, ...])
*   metrics.mean_squared_log_error(y_ test, y_pred)
*   metrics.median_absolute_error(y_ test, y_pred)
*   metrics.r2_score(y_ test, y_pred[, ...])



---

# Tasks
The main aim of these tasks is to get familiar with Linear Regression problems. Apply LinearRegression to the following datasets. Note the error obtained and coefficients
*   **dataset1.csv** - a synthetic dataset including 5 points (1-dimensional data) with one target
*   **dataset2.csv** - a synthetic dataset including 1000 points (3-dimensional data) with one target variable. The variables are named x1, x2, x3, y. y is the variable to be regressed. Split the dataset into training set and test set (70% for training set and 30% for test set).

# Task 2.1. dataset1.csv

In [5]:
#code
dataset = pd.read_csv("dataset1.csv")
x_train = dataset[['x']]
y_train = dataset[['y']]
regressor = LinearRegression()
regressor.fit(x_train, y_train)

print(regressor.intercept_)
print(regressor.coef_)

y_pred = regressor.predict(x_train)
print(y_pred)

[0.4]
[[0.8]]
[[1.2]
 [2. ]
 [3.6]
 [2.8]
 [4.4]]

In [6]:

r2 = metrics.r2_score(y_train, y_pred)
r2

0.7272727272727273

# Task 2.2. dataset2.csv

In [7]:
#code
dataset = pd.read_csv("dataset2.csv")
x = dataset[['x1', 'x2', 'x3']]
y = dataset[['y']]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)
regressor = LinearRegression()
regressor.fit(x_train, y_train)

print(regressor.intercept_)
print(regressor.coef_)

y_pred = regressor.predict(x_test)
print(y_pred)

r2 = metrics.r2_score(y_test, y_pred)
r2

[4.00001817]
[[2.99999344 3.99999127 4.99999257]]
[[ -1.09555578]
 [  2.8210162 ]
 [ -2.80937088]
 [  0.93249028]
 [  4.46716831]
 [ 18.10287426]
 [-17.89014239]
 [  9.33475504]
 [  4.2172295 ]
 [ 23.10458022]
 [  7.45103989]
 [  8.46790232]
 [ 18.21853963]
 [ -4.1790449 ]
 [  6.84075532]
 [  2.95235554]
 [  8.85771318]
 [ -0.74380608]
 [ 15.01121205]
 [ 10.95829732]
 [-18.12084033]
 [ -4.44901511]
 [ -0.8096726 ]
 [ 22.74597955]
 [-13.42213109]
 [ 18.65213357]
 [  9.02682145]
 [ -4.48153144]
 [ 10.20839999]
 [ 14.95625146]
 [  6.46187879]
 [ 12.21761812]
 [  0.73402813]
 [  8.62311167]
 [ -4.17021239]
 [-12.78144779]
 [ 15.66638407]
 [ 20.62849828]
 [ -0.59142472]
 [ -5.31117429]
 [ 10.51840672]
 [ -5.39886769]
 [  3.65505324]
 [  0.34790187]
 [-16.12786455]
 [ 12.34775266]
 [ -1.38894906]
 [ -8.73713617]
 [  4.38949713]
 [  0.48892861]
 [  3.38194285]
 [ -1.95872119]
 [  8.98117513]
 [  2.69226911]
 [ 13.72273929]
 [ -0.72766663]
 [  9.27256349]
 [  0.89347602]
 [  9.19869181]
 [  8.09576538]
 [  7.70930563]
 [ 20.48890725]
 [  6.02816454]
 [  0.30307559]
 [  3.41876931]
 [  8.69541   ]
 [ -1.57929563]
 [  9.70137965]
 [  8.42162816]
 [ -9.76255447]
 [  4.42876172]
 [ 23.19048328]
 [ -0.59056618]
 [ 17.12417478]
 [  6.29319268]
 [ 11.35595117]
 [  5.91645534]
 [  4.04949412]
 [ 14.82501594]
 [ 13.91609947]
 [ 16.57863245]
 [ 10.05090673]
 [ 20.39200723]
 [-13.82624723]
 [  3.19037145]
 [ 15.32179833]
 [  8.19621407]
 [-18.12394126]
 [ -7.3958439 ]
 [  9.05007992]
 [ -6.68543175]
 [  2.87701779]
 [ -9.16907075]
 [ 14.96197225]
 [ -7.0628637 ]
 [  2.86743447]
 [-11.27385279]
 [ 11.40577881]
 [ 14.89100175]
 [  2.9120818 ]
 [ 17.11914276]
 [ 12.99156341]
 [  4.53960167]
 [  7.71087742]
 [ 24.24697908]
 [ -5.81460852]
 [  2.53611294]
 [  2.97515511]
 [  1.18982834]
 [ 10.09590779]
 [ -4.10326899]
 [  9.99342968]
 [ -5.77076762]
 [ -4.14904469]
 [ -3.13077179]
 [  2.9302074 ]
 [ -1.309975  ]
 [-12.47117089]
 [  9.37095684]
 [  9.06351491]
 [ -6.76784059]
 [  3.44855575]
 [ -6.16315923]
 [ -6.82170581]
 [-15.64679171]
 [ 13.51612022]
 [  7.67144476]
 [ -2.40506216]
 [  5.36431657]
 [ -4.85346662]
 [-13.20117471]
 [  4.31524342]
 [  4.57064306]
 [ 10.26768676]
 [ 12.2194487 ]
 [  7.42819772]
 [ -7.28432337]
 [ -6.73674249]
 [  3.81042711]
 [  4.13722109]
 [  3.22157274]
 [  1.43283724]
 [ -1.75847576]
 [  5.55149621]
 [ 16.89116709]
 [  5.01574152]
 [  3.58559941]
 [  5.05492475]
 [ 20.34328641]
 [ -0.78207258]
 [ -9.45975566]
 [ 12.09530998]
 [ -6.80541197]
 [  0.74385332]
 [  4.38891365]
 [  2.37301909]
 [ 24.2520517 ]
 [ 13.2966039 ]
 [ 13.41470076]
 [ 19.99043639]
 [  4.06808273]
 [  8.01558645]
 [  3.67054585]
 [ 10.47850813]
 [  6.05060078]
 [  9.34436764]
 [ -5.431008  ]
 [-14.49704433]
 [ 12.03808225]
 [  4.90872447]
 [ 16.54680563]
 [ 11.50475984]
 [ 13.38180328]
 [ -8.22956365]
 [ 19.32188222]
 [  1.5400456 ]
 [  3.57865607]
 [  9.16850844]
 [ -8.51519714]
 [ 16.79943566]]

0.999999999411653

# Task 2.3. Apply LinearRegression to the following dataset:
*   Red wine quality: https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv . The dataset includes info about the chemical properties of different types of wine and how they relate to overall quality.

In [17]:
from sklearn.base import re
#code
dataset = pd.read_csv("winequality-red.csv", sep = ';')

dataset
x = dataset.drop(['quality'], axis=1)
y = dataset[['quality']]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)
regressor = LinearRegression()
regressor.fit(x_train, y_train)
print(regressor.intercept_)
print(regressor.coef_)

y_pred = regressor.predict(x_test)
print(y_pred)

     

r2 = metrics.r2_score(y_test, y_pred)
r2

[36.54693744]
[[ 4.58527906e-02 -1.17640321e+00 -2.87778222e-01  1.64922765e-02
  -1.80636202e+00  6.07141383e-03 -3.77903394e-03 -3.26155240e+01
  -3.75065394e-01  8.87110235e-01  2.67134606e-01]]
[[5.54096565]
 [5.36989645]
 [6.10505858]
 [5.74193275]
 [6.70446788]
 [5.99284464]
 [6.21945794]
 [5.06042533]
 [5.76434777]
 [5.16110692]
 [6.20053845]
 [5.3581788 ]
 [5.57545788]
 [6.48751434]
 [5.6342095 ]
 [5.36206798]
 [5.9692357 ]
 [5.42284425]
 [5.61642209]
 [5.42472535]
 [5.76425606]
 [6.19843286]
 [5.38347544]
 [6.44302873]
 [5.4465834 ]
 [6.30871137]
 [6.12437492]
 [5.66115672]
 [5.32571352]
 [5.75947059]
 [5.26190019]
 [6.39964188]
 [5.21608271]
 [6.3101122 ]
 [4.91013636]
 [5.74700718]
 [5.2994134 ]
 [5.3763176 ]
 [6.36843078]
 [5.07493841]
 [6.07589215]
 [5.03970156]
 [5.22425778]
 [6.17544669]
 [5.11529364]
 [5.79466462]
 [5.10602686]
 [5.26060517]
 [5.09219633]
 [6.06257072]
 [5.64917257]
 [5.46669867]
 [6.26296816]
 [4.8129872 ]
 [5.09380039]
 [5.99017093]
 [6.07420349]
 [5.96541377]
 [5.84445539]
 [5.24387716]
 [6.3150529 ]
 [5.20743892]
 [5.29521589]
 [5.52980205]
 [4.60116074]
 [5.4230996 ]
 [6.67149216]
 [5.68372413]
 [5.79264509]
 [6.45080761]
 [4.91013636]
 [6.37464982]
 [5.67657729]
 [5.7813521 ]
 [5.40103675]
 [5.28024277]
 [6.14242939]
 [5.36181421]
 [5.70320172]
 [5.81640495]
 [6.0481553 ]
 [5.1162689 ]
 [4.98113258]
 [5.54375599]
 [5.6239067 ]
 [5.10267216]
 [5.31619731]
 [6.11261052]
 [5.39072787]
 [5.8400811 ]
 [5.24577683]
 [6.30035493]
 [5.06118166]
 [6.22940663]
 [6.11859591]
 [5.32993368]
 [6.31305032]
 [5.45625428]
 [4.80715091]
 [6.25816213]
 [5.48922384]
 [5.41898436]
 [5.33522178]
 [4.95008495]
 [4.83647004]
 [5.35638358]
 [5.79736995]
 [5.44451105]
 [6.00155158]
 [6.47572658]
 [6.50408025]
 [5.4548076 ]
 [6.18850084]
 [5.47821564]
 [4.98412617]
 [6.66464824]
 [5.29170309]
 [4.95471792]
 [5.1541742 ]
 [5.21394493]
 [4.89217696]
 [6.61905169]
 [6.44781321]
 [5.03778934]
 [5.35140396]
 [5.55136321]
 [5.93449246]
 [5.16716205]
 [6.21574499]
 [5.78788581]
 [5.69315725]
 [5.15154495]
 [6.29180391]
 [5.00920877]
 [5.91483355]
 [5.92591087]
 [5.09863779]
 [6.55017235]
 [5.28004749]
 [5.43087905]
 [5.1200417 ]
 [5.39740589]
 [5.76662845]
 [5.30447339]
 [6.02593774]
 [6.39046405]
 [5.64305973]
 [4.75110139]
 [5.78410554]
 [5.89935727]
 [5.50932656]
 [6.52510551]
 [5.1504104 ]
 [5.22458396]
 [6.08868692]
 [6.19859291]
 [6.27820671]
 [6.22112511]
 [5.9396637 ]
 [5.42862629]
 [6.16907165]
 [5.80754243]
 [5.12098279]
 [5.15338934]
 [6.39838837]
 [5.96849944]
 [5.73780675]
 [5.11230197]
 [5.25043017]
 [5.96632303]
 [5.17835116]
 [6.04359209]
 [4.99228738]
 [5.06943444]
 [6.38745718]
 [5.35457414]
 [5.43328014]
 [4.96037983]
 [5.470341  ]
 [5.32993368]
 [5.68208587]
 [6.241903  ]
 [5.7347586 ]
 [5.80960306]
 [6.40683596]
 [6.73586395]
 [6.36512297]
 [5.5746778 ]
 [5.14905702]
 [4.88703173]
 [5.47889667]
 [5.72312852]
 [5.44742103]
 [4.97345064]
 [5.90822704]
 [5.27688592]
 [5.68809631]
 [5.54976994]
 [5.51086946]
 [5.30025206]
 [6.18374197]
 [5.61157599]
 [6.27383933]
 [5.08451716]
 [6.61524638]
 [5.91259032]
 [5.26266248]
 [4.9344117 ]
 [6.29410371]
 [5.77053464]
 [5.70144494]
 [6.05711571]
 [5.33522178]
 [6.30309906]
 [5.31365146]
 [5.13382721]
 [5.23857128]
 [5.05069214]
 [6.0054287 ]
 [5.60595029]
 [5.75015141]
 [5.28099788]
 [5.07029304]
 [5.10782672]
 [5.98395189]
 [5.62486662]
 [5.73103564]
 [5.76971825]
 [6.59946025]
 [5.76081456]
 [5.29005169]
 [5.07869972]
 [6.15536022]
 [6.16062456]
 [5.45236614]
 [5.27394248]
 [6.24496369]
 [5.00224228]
 [5.57829267]
 [5.40642599]
 [5.94770506]
 [6.01819101]
 [5.84477697]
 [5.45256163]
 [5.73921367]
 [6.63308493]
 [5.84423071]
 [5.34594548]
 [4.87012455]
 [5.40139137]
 [4.98823002]
 [5.16087021]
 [6.62618906]
 [5.76018221]
 [6.34494816]
 [5.05946388]
 [5.19349088]
 [4.8451953 ]
 [5.31331692]
 [5.96780961]
 [5.94560348]
 [5.50538977]
 [5.60901985]
 [5.44891792]
 [5.44886612]
 [5.78410554]
 [5.62826973]
 [5.14201716]
 [4.93031878]
 [6.22829298]
 [5.47147435]
 [5.73672607]
 [5.10436413]
 [6.42767695]
 [4.95694941]
 [5.76503117]
 [4.96521094]
 [6.04359209]
 [5.48431381]
 [5.34150057]
 [6.7301553 ]
 [5.78790816]
 [5.64309306]
 [4.98117185]
 [5.11333868]
 [5.93550139]
 [5.65078925]
 [5.86192869]
 [4.81573921]
 [5.71129951]
 [5.73696435]
 [5.9692357 ]
 [5.59977052]
 [5.30498782]
 [6.34769791]
 [6.09585751]
 [4.97339166]
 [6.35820168]
 [5.13027193]
 [5.55802518]
 [5.63834912]
 [6.26231676]
 [4.92217983]
 [5.76921527]
 [5.52661526]
 [5.49514583]
 [4.79103486]
 [6.27965397]
 [5.74739698]
 [4.88146752]
 [5.50031048]
 [5.73308832]
 [5.42139254]
 [6.60740846]
 [5.49611891]
 [5.74352352]
 [5.02401183]
 [5.13958174]
 [6.18847339]
 [6.24496369]
 [5.27346387]
 [5.7348706 ]
 [6.96951925]
 [5.02876452]
 [5.27688592]
 [5.28372856]
 [5.07371132]
 [6.60740267]
 [5.78595147]
 [5.53470269]
 [5.97356401]
 [4.90638128]
 [5.14649939]
 [5.56237794]
 [5.4320231 ]
 [5.14006687]
 [6.08802242]
 [6.30309906]
 [5.57903018]
 [5.60183539]
 [5.25178884]
 [5.61388425]
 [5.6610455 ]
 [5.70430205]
 [5.46171746]
 [6.79642446]
 [6.2166233 ]
 [5.53205685]
 [5.24626431]
 [5.35224094]
 [6.05711571]
 [6.71105135]
 [5.41995413]
 [6.34323065]
 [5.50371873]
 [5.18136405]
 [6.63026187]
 [6.48751434]
 [5.09863779]
 [4.2084594 ]
 [4.97562503]
 [6.1147991 ]
 [5.05114562]
 [6.57741839]
 [5.54617238]
 [5.17461477]
 [5.41886298]
 [5.22390583]
 [5.92128507]
 [5.27394248]
 [5.52203289]
 [5.5780536 ]
 [5.3083552 ]
 [5.54947637]
 [5.21273836]
 [5.85465565]
 [6.80485006]
 [6.59978346]
 [5.13382721]
 [6.03898891]
 [6.12970165]
 [5.9903675 ]
 [6.13628849]
 [5.88848537]
 [5.53239865]
 [6.25918824]
 [5.0370858 ]
 [5.77987603]
 [5.71203131]
 [5.5941649 ]
 [5.11651116]
 [5.78380744]
 [5.19061146]
 [5.89608807]
 [5.34485166]
 [5.77822332]
 [5.39072787]
 [6.15536022]
 [5.15360646]
 [6.14517287]
 [5.7861498 ]
 [4.9949012 ]
 [6.0004085 ]
 [5.14227209]
 [5.51776012]
 [5.76378234]
 [5.35551844]
 [5.80034005]
 [5.11719397]
 [6.38992524]
 [6.16190822]
 [5.13773395]
 [5.96780961]
 [4.9858028 ]
 [5.52928087]
 [5.83445751]
 [5.04582033]
 [6.22997202]
 [5.57285792]
 [5.05081781]
 [5.3603563 ]
 [6.00463529]
 [6.01770903]
 [5.51239388]
 [5.09239226]
 [6.12821737]
 [6.26277435]
 [5.39517385]
 [5.10866511]
 [6.89779681]
 [5.13545298]
 [5.53070187]
 [5.34594548]
 [5.05073898]
 [5.05069214]
 [5.22112178]
 [5.74546419]
 [5.21971187]
 [5.6021073 ]
 [6.20711668]
 [6.02032444]
 [5.67222596]
 [5.66146687]
 [6.26805628]
 [5.29521589]
 [5.30344888]
 [4.96707612]
 [5.53512166]
 [5.60014701]
 [5.41299152]
 [5.41597648]
 [5.63411812]
 [5.82479262]
 [6.12196007]
 [5.62975902]
 [5.57829267]
 [6.35245074]
 [5.14218929]
 [6.46318376]
 [5.21948034]
 [4.86593955]
 [5.48431381]
 [5.3327878 ]
 [5.6934289 ]
 [5.29799379]
 [4.67794133]
 [4.98160403]
 [5.66725219]
 [6.44577451]
 [6.3556978 ]
 [5.15137316]
 [6.35159113]
 [5.44710448]
 [6.22354503]
 [5.75015141]
 [5.96849944]
 [5.88874354]
 [5.16703079]
 [5.75664255]
 [6.0075376 ]]

0.3186005776026659

# Task 2.4. Apply LinearRegression to the following dataset:
*   Energy efficiency: https://archive.ics.uci.edu/ml/datasets/Energy+efficiency.

In [18]:

#code
dataset = pd.read_excel("ENB2012_data.xlsx")
dataset
x = dataset[['X1', 'X2', 'X3', 'X4','X5','X6','X7','X8']]
y1 = dataset[['Y1']]
y2 = dataset[['Y2']]

x_train, x_test, y1_train, y1_test, y2_train, y2_test = train_test_split(x, y1, y2, test_size=0.3, random_state=1)
regressor1 = LinearRegression()
regressor1.fit(x_train, y1_train)
regressor2 = LinearRegression()
regressor2.fit(x_train, y2_train)

print(regressor1.intercept_)
print(regressor1.coef_)
print(regressor2.intercept_)
print(regressor2.coef_)

y_pred1 = regressor1.predict(x_test)
print(y_pred1)
y_pred2 = regressor2.predict(x_test)
print(y_pred2)

[80.88875028]
[[-6.24773307e+01 -6.08177832e-02  3.52657449e-02 -4.80417641e-02
   4.17049559e+00  4.20223146e-02  1.99397468e+01  2.11058425e-01]]
[104.37765051]
[[-7.41167713e+01 -7.17332169e-02  2.33646665e-02 -4.75489417e-02
   4.11598430e+00  2.10253526e-01  1.49232091e+01  5.54898306e-02]]
[[13.12064806]
 [27.47098304]
 [33.45290707]
 [32.50930958]
 [34.12810466]
 [15.23500767]
 [12.28606796]
 [28.37938926]
 [15.09745608]
 [26.31199281]
 [17.81350644]
 [30.46194505]
 [31.72515376]
 [17.26437579]
 [13.0671411 ]
 [32.63537652]
 [27.22832298]
 [17.72851495]
 [15.73151554]
 [33.71370958]
 [31.93621219]
 [ 8.58445696]
 [28.60717795]
 [18.1409782 ]
 [13.89118341]
 [33.62194318]
 [18.42737451]
 [12.95161195]
 [35.71133002]
 [16.02573441]
 [31.15929285]
 [33.24184865]
 [11.28245175]
 [16.60723377]
 [26.90314577]
 [35.96441076]
 [18.43702811]
 [11.02937101]
 [32.84643495]
 [15.18150071]
 [36.5776578 ]
 [11.87360471]
 [10.15542589]
 [12.15905417]
 [10.37222899]
 [11.694915  ]
 [23.98089276]
 [31.59813997]
 [33.95906855]
 [32.720368  ]
 [ 9.78107603]
 [30.67300348]
 [ 9.66371584]
 [15.3093987 ]
 [34.33602125]
 [34.50505736]
 [33.32589328]
 [29.30295483]
 [11.6174413 ]
 [17.09533968]
 [13.16267038]
 [28.05899415]
 [28.39611952]
 [34.37804356]
 [27.10225603]
 [40.3708312 ]
 [31.30303691]
 [17.85552875]
 [30.84203959]
 [14.82254442]
 [26.18592587]
 [15.35142101]
 [14.60840332]
 [32.80102518]
 [16.64925608]
 [31.38166268]
 [29.68304936]
 [33.50265115]
 [15.52045712]
 [25.6835303 ]
 [10.9873487 ]
 [29.89410779]
 [15.72097775]
 [34.08294051]
 [14.81946174]
 [39.48457519]
 [40.11775046]
 [36.74669391]
 [15.64747092]
 [12.73001574]
 [29.59900473]
 [25.00833271]
 [11.45148786]
 [33.74801013]
 [16.05810312]
 [30.8840619 ]
 [11.32447407]
 [31.34505923]
 [ 8.07829549]
 [34.92717421]
 [34.38890717]
 [16.48021997]
 [28.81823637]
 [11.82849972]
 [16.19565471]
 [12.86573628]
 [28.10101647]
 [27.64001915]
 [29.0292948 ]
 [37.08476613]
 [39.94871435]
 [22.84532192]
 [26.86112345]
 [11.40638287]
 [37.37986918]
 [ 9.95976574]
 [29.34931145]
 [31.83449044]
 [32.25189453]
 [16.6912784 ]
 [26.39698429]
 [28.25237547]
 [15.77265367]
 [26.22794818]
 [32.4243181 ]
 [16.39617534]
 [ 8.75349307]
 [34.54707967]
 [ 9.87477426]
 [15.48808841]
 [35.3732578 ]
 [10.62530973]
 [32.29391685]
 [35.75335234]
 [ 7.66008756]
 [30.99025674]
 [25.64150798]
 [ 9.44785958]
 [32.93142643]
 [13.8491611 ]
 [17.4334119 ]
 [28.27005258]
 [19.1025721 ]
 [14.89693545]
 [22.71925497]
 [29.26093251]
 [ 7.95128169]
 [36.53563549]
 [29.39133377]
 [15.8470447 ]
 [12.19053869]
 [26.69208734]
 [34.67409347]
 [35.83739697]
 [17.51745653]
 [18.22596968]
 [29.7714283 ]
 [12.99275007]
 [32.34027347]
 [15.10799387]
 [25.89598336]
 [28.7594838 ]
 [32.88506981]
 [15.43458145]
 [32.7160337 ]
 [12.23439205]
 [32.92709212]
 [29.60239219]
 [18.72247756]
 [18.68045525]
 [12.07500954]
 [36.87370771]
 [32.59335421]
 [14.72789934]
 [11.19840712]
 [31.62343202]
 [11.28031593]
 [32.97344874]
 [33.14248485]
 [14.64385471]
 [34.04091819]
 [ 9.40583727]
 [28.88555074]
 [28.10415831]
 [33.46062884]
 [ 9.11553204]
 [11.40946555]
 [28.18820294]
 [12.69853121]
 [11.94799574]
 [14.90658905]
 [33.6639655 ]
 [33.75573189]
 [28.73419174]
 [11.78647741]
 [32.50497527]
 [ 7.61806524]
 [30.19354515]
 [ 8.50041233]
 [39.73765593]
 [18.47905042]
 [29.72940599]
 [18.31001431]
 [14.18936914]
 [25.93800568]
 [17.18033116]
 [33.79775421]
 [ 9.82309835]
 [14.23139146]
 [14.31543609]
 [32.55133189]
 [26.52305123]
 [27.14427835]
 [12.85608268]
 [ 9.53764889]
 [32.80441263]
 [12.40159712]
 [27.55502766]
 [14.4844722 ]
 [31.09197849]
 [31.47207302]
 [14.52435869]
 [28.54842537]
 [10.07138126]
 [25.85256641]
 [34.71611578]
 [25.81054409]
 [39.77967824]
 [14.35532258]
 [24.10695971]
 [34.17784874]]
[[15.33739547]
 [29.91374082]
 [34.39070357]
 [34.22990733]
 [34.76742658]
 [17.01282755]
 [14.9845997 ]
 [29.80333815]
 [17.45175389]
 [29.74858168]
 [19.00949281]
 [32.15222219]
 [33.51266686]
 [19.26353037]
 [16.19682886]
 [34.8606679 ]
 [31.01888596]
 [19.58476355]
 [17.67515071]
 [35.54997087]
 [33.56815669]
 [12.52329403]
 [31.63920271]
 [19.82657966]
 [16.62353376]
 [34.23593987]
 [19.4376352 ]
 [15.49215917]
 [36.52387853]
 [18.09422026]
 [31.9863297 ]
 [34.33521374]
 [14.78656762]
 [18.18127268]
 [29.70479765]
 [36.78962189]
 [19.30679875]
 [14.52082427]
 [34.91615774]
 [17.87226094]
 [38.15346946]
 [14.74278359]
 [13.98813246]
 [15.34961692]
 [13.43856658]
 [15.02838373]
 [27.57001036]
 [33.87768408]
 [34.92219028]
 [34.28539716]
 [13.48235061]
 [32.20771202]
 [13.71653138]
 [17.56417105]
 [35.8504221 ]
 [35.6956584 ]
 [34.75572079]
 [31.98706305]
 [14.97202893]
 [19.41829406]
 [15.547649  ]
 [30.89746247]
 [31.58371288]
 [36.06067562]
 [30.38812538]
 [40.40365663]
 [33.4016872 ]
 [19.21974633]
 [32.05294833]
 [16.77101143]
 [29.1178211 ]
 [17.77442457]
 [17.2105103 ]
 [33.76125334]
 [18.3915262 ]
 [34.36717734]
 [31.88778919]
 [35.49448104]
 [17.61966088]
 [28.04085366]
 [14.31057074]
 [31.94327902]
 [17.74905983]
 [35.58467874]
 [17.26600013]
 [39.97144378]
 [40.13791327]
 [37.99870577]
 [17.25464366]
 [15.51057846]
 [31.46728214]
 [27.66413065]
 [14.63180393]
 [34.86670045]
 [18.43531024]
 [32.26320185]
 [14.99682115]
 [33.61194072]
 [11.99180732]
 [35.80663806]
 [35.92669389]
 [18.5462899 ]
 [31.69469254]
 [15.02751876]
 [17.9963839 ]
 [16.01050258]
 [31.107716  ]
 [29.75897713]
 [31.75018237]
 [37.68917838]
 [40.29267697]
 [26.32657343]
 [29.49454412]
 [14.9165391 ]
 [38.16517526]
 [13.19675046]
 [32.14618965]
 [32.36305271]
 [34.0152909 ]
 [18.60177973]
 [29.17331093]
 [30.16835537]
 [17.8284769 ]
 [29.32807463]
 [34.80517807]
 [18.12578285]
 [12.36853033]
 [35.90591193]
 [13.77202121]
 [17.2785709 ]
 [36.83340592]
 [13.70430993]
 [34.22554442]
 [36.73413206]
 [12.35504692]
 [32.14109339]
 [27.83060014]
 [13.27031946]
 [34.34088699]
 [16.41328023]
 [19.10876667]
 [30.9529523 ]
 [19.81435822]
 [17.32235494]
 [25.69581285]
 [31.77680953]
 [12.35682454]
 [37.94321594]
 [32.35644318]
 [18.37982041]
 [15.63377957]
 [29.64930781]
 [35.54089471]
 [37.15463911]
 [19.52927372]
 [19.25130892]
 [32.25716931]
 [15.64548536]
 [34.38467102]
 [17.37784477]
 [29.55990525]
 [29.70406429]
 [34.18176039]
 [18.13800429]
 [34.33652408]
 [14.90518262]
 [34.39201392]
 [32.41193301]
 [19.91363208]
 [19.70337856]
 [14.92910987]
 [37.63368855]
 [34.65041438]
 [17.47711863]
 [14.36606057]
 [32.30756288]
 [14.28577852]
 [34.55114051]
 [34.39637682]
 [17.05661158]
 [35.37442521]
 [13.06006594]
 [30.33482487]
 [30.08021031]
 [35.28422751]
 [12.97479114]
 [14.4215504 ]
 [30.50071736]
 [15.22641581]
 [15.29412709]
 [17.19151849]
 [34.4461934 ]
 [35.76022439]
 [31.27418549]
 [14.81726523]
 [34.28103425]
 [12.14479339]
 [32.36814897]
 [12.10278698]
 [40.23718714]
 [19.51705227]
 [32.04691579]
 [19.67181597]
 [16.60454194]
 [29.77015878]
 [18.84302331]
 [35.97047792]
 [13.69260414]
 [16.81479547]
 [17.23530252]
 [34.44016085]
 [29.80407151]
 [30.59837891]
 [16.14133903]
 [13.0857708 ]
 [34.70590421]
 [15.6892694 ]
 [30.33424787]
 [17.08053882]
 [33.34619737]
 [33.2469235 ]
 [16.79000325]
 [29.64857446]
 [13.5676254 ]
 [27.88608997]
 [35.75114823]
 [27.67583644]
 [40.44744066]
 [16.94476694]
 [28.20077093]
 [35.87120405]]

# Finally,
Save a copy in your Github. Remember renaming the notebook.